// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/greeting/greeting.proto

package go_micro_service_greeting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Greeting service

func NewGreetingEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Greeting service

type GreetingService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Greeting_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Greeting_PingPongService, error)
}

type greetingService struct {
	c    client.Client
	name string
}

func NewGreetingService(name string, c client.Client) GreetingService {
	return &greetingService{
		c:    c,
		name: name,
	}
}

func (c *greetingService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Greeting.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Greeting_StreamService, error) {
	req := c.c.NewRequest(c.name, "Greeting.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &greetingServiceStream{stream}, nil
}

type Greeting_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type greetingServiceStream struct {
	stream client.Stream
}

func (x *greetingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *greetingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *greetingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greetingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greetingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetingService) PingPong(ctx context.Context, opts ...client.CallOption) (Greeting_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Greeting.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &greetingServicePingPong{stream}, nil
}

type Greeting_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type greetingServicePingPong struct {
	stream client.Stream
}

func (x *greetingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *greetingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *greetingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greetingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greetingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *greetingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Greeting service

type GreetingHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Greeting_StreamStream) error
	PingPong(context.Context, Greeting_PingPongStream) error
}

func RegisterGreetingHandler(s server.Server, hdlr GreetingHandler, opts ...server.HandlerOption) error {
	type greeting interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Greeting struct {
		greeting
	}
	h := &greetingHandler{hdlr}
	return s.Handle(s.NewHandler(&Greeting{h}, opts...))
}

type greetingHandler struct {
	GreetingHandler
}

func (h *greetingHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GreetingHandler.Call(ctx, in, out)
}

func (h *greetingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GreetingHandler.Stream(ctx, m, &greetingStreamStream{stream})
}

type Greeting_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type greetingStreamStream struct {
	stream server.Stream
}

func (x *greetingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *greetingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *greetingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greetingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greetingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *greetingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GreetingHandler.PingPong(ctx, &greetingPingPongStream{stream})
}

type Greeting_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type greetingPingPongStream struct {
	stream server.Stream
}

func (x *greetingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *greetingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *greetingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greetingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greetingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *greetingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
